version: "3.8"
services: 
    mysql-server:
        image: "mysql:8.0.25"
        environment: 
            - MYSQL_ROOT_PASSWORD=root123    
    grafana-server:
        build: grafana
        ports:
            - '3000:3000'
    myapp:
        build: .
        ports:
            - '5000:5000'
        command: microburst_incast_heavyhitter5
        depends_on: 
            - mysql-server
            - grafana-server
